# Generated by Django 4.2.29 on 2026-03-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balancehistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='balancehistory',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_account_date'),
        ),
    ]
