# Generated by Django 4.2.28 on 2026-02-21 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('security_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('bond', 'Bond'), ('crypto', 'Cryptocurrency'), ('option', 'Option'), ('other', 'Other')], default='stock', max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'securities',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('split', 'Split')], max_length=10)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=14)),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='accounts.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'trade histories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='portfolio.security')),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['-date'],
                'unique_together': {('security', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=6, max_digits=14)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['security__symbol'],
                'unique_together': {('user', 'account', 'security')},
            },
        ),
    ]
