# Generated by Django 4.2.29 on 2026-03-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_alter_holding_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTaxLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('date_disposed', models.DateField(blank=True, null=True)),
                ('proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('holding_period', models.CharField(choices=[('short_term', 'Short-Term'), ('long_term', 'Long-Term'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('source', models.CharField(blank=True, help_text="e.g., 'coinbase', '1099-da'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_tax_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_disposed'],
            },
        ),
    ]
