# Generated by Django 4.2.29 on 2026-03-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_crypto_tax_lot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cryptotaxlot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='security',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'security'), name='unique_user_account_security'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('security', 'date'), name='unique_security_price_date'),
        ),
    ]
