# Generated by Django 4.2.28 on 2026-02-25 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(help_text='Plaid item_id', max_length=255, unique=True)),
                ('_access_token', models.TextField(db_column='access_token', help_text='Encrypted Plaid access token')),
                ('plaid_institution_id', models.CharField(help_text='Plaid institution ID', max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('expired', 'Expired')], default='active', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, help_text='Link to local Institution record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaid_items', to='accounts.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Plaid account_id', max_length=255)),
                ('cursor', models.TextField(blank=True, help_text='Plaid sync cursor for incremental sync')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaid_sync_cursors', to='accounts.account')),
                ('plaid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to='integrations.plaiditem')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('plaid_item', 'account_id')},
            },
        ),
    ]
