# Generated by Django 4.2.28 on 2026-02-21 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('married_joint', 'Married Filing Jointly'), ('married_separate', 'Married Filing Separately'), ('head_of_household', 'Head of Household')], default='single', max_length=30)),
                ('federal_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('state_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('user', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('w2', 'W-2'), ('1099_int', '1099-INT'), ('1099_div', '1099-DIV'), ('1099_b', '1099-B'), ('1099_misc', '1099-MISC'), ('1099_nec', '1099-NEC'), ('1098', '1098'), ('k1', 'K-1'), ('other', 'Other')], max_length=20)),
                ('issuer', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='taxes.taxyear')),
            ],
            options={
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='DeductibleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('standard', 'Standard Deduction'), ('mortgage_interest', 'Mortgage Interest'), ('state_local_tax', 'State & Local Tax'), ('charitable', 'Charitable Donations'), ('medical', 'Medical Expenses'), ('business', 'Business Expenses'), ('education', 'Education'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='taxes.taxyear')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
