# Generated by Django 4.2.29 on 2026-03-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_receipt_accept_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductibleexpense',
            name='turbotax_category',
            field=models.CharField(blank=True, help_text='TurboTax category grouping', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxdocument',
            name='document_type',
            field=models.CharField(choices=[('w2', 'W-2'), ('1099_int', '1099-INT'), ('1099_div', '1099-DIV'), ('1099_b', '1099-B'), ('1099_misc', '1099-MISC'), ('1099_nec', '1099-NEC'), ('1099_da', '1099-DA'), ('1098', '1098'), ('k1', 'K-1'), ('other', 'Other')], max_length=20),
        ),
    ]
