# Generated by Django 4.2.29 on 2026-03-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_add_turbotax_and_1099da'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxyear',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deductibleexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taxdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='taxyear',
            constraint=models.UniqueConstraint(fields=('user', 'year'), name='unique_user_tax_year'),
        ),
    ]
