# Generated by Django 4.2.28 on 2026-02-25 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxes', '0003_receipt_accept_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('imap', 'IMAP')], max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('_credentials', models.TextField(db_column='credentials', default='', help_text='Encrypted OAuth tokens or IMAP credentials (JSON)')),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='EmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('from_pattern', models.CharField(blank=True, help_text='Regex or substring to match sender email/name', max_length=500)),
                ('subject_pattern', models.CharField(blank=True, help_text='Regex or substring to match subject line', max_length=500)),
                ('has_attachment', models.BooleanField(blank=True, help_text='True = must have attachment, False = must not, None = either', null=True)),
                ('action', models.CharField(choices=[('process_receipt', 'Process as Receipt'), ('ignore', 'Ignore'), ('archive', 'Archive')], max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Email Message-ID header', max_length=500, unique=True)),
                ('from_address', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_sync.emailaccount')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_messages', to='email_sync.emailrule')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_sync.emailmessage')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_attachments', to='taxes.receipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
