# Generated by Django 4.2.29 on 2026-03-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='_credentials',
            field=models.TextField(db_column='credentials', default='', help_text='Encrypted IMAP credentials (JSON)'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('imap', 'IMAP')], max_length=10),
        ),
    ]
