# Generated by Django 4.2.28 on 2026-03-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='accounts.account'),
        ),
    ]
