# Generated by Django 4.2.29 on 2026-03-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_make_account_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='bank_profile',
            field=models.CharField(blank=True, help_text='Detected bank profile ID', max_length=50),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_institution',
            field=models.CharField(blank=True, help_text='Bank or institution name', max_length=100),
        ),
    ]
