# Generated by Django 4.2.29 on 2026-03-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0003_add_bank_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('asin', models.CharField(blank=True, max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_orders', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
