# Generated by Django 4.2.28 on 2026-02-25 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrule',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='True if created automatically from user corrections'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('possibly_cancelled', 'Possibly Cancelled'), ('cancellation_pending', 'Cancellation Pending')], default='active', max_length=25)),
                ('confidence', models.FloatField(default=0.0, help_text='Detection confidence score 0-1')),
                ('last_charged', models.DateField(blank=True, null=True)),
                ('next_expected', models.DateField(blank=True, null=True)),
                ('cancellation_url', models.URLField(blank=True)),
                ('cancellation_method', models.CharField(blank=True, help_text='web, email, phone', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount'],
                'unique_together': {('user', 'merchant')},
            },
        ),
    ]
