# Generated by Django 4.2.28 on 2026-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_expected',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('possibly_cancelled', 'Possibly Cancelled'), ('cancellation_pending', 'Cancellation Pending')], db_index=True, default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], db_index=True, default='expense', max_length=10),
        ),
    ]
