# Generated by Django 4.2.29 on 2026-03-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
