# Generated by Django 4.2.28 on 2026-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('urgent', 'Urgent')], db_index=True, default='info', max_length=10),
        ),
    ]
