# Generated by Django 4.2.28 on 2026-03-03 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='fiscal_year_start',
            field=models.PositiveSmallIntegerField(default=1, help_text='Month number (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
